<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUgVpRh4\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUgVpRh4/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerUgVpRh4.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerUgVpRh4\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerUgVpRh4\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'UgVpRh4',
    'container.build_id' => '5665222c',
    'container.build_time' => 1550334929,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUgVpRh4');
