<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container0dQQJVK\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container0dQQJVK/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container0dQQJVK.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container0dQQJVK\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \Container0dQQJVK\srcApp_KernelDevDebugContainer([
    'container.build_hash' => '0dQQJVK',
    'container.build_id' => '61d6fd4c',
    'container.build_time' => 1549904902,
], __DIR__.\DIRECTORY_SEPARATOR.'Container0dQQJVK');
